### ISSUE TITLE
Use the api key in the workspace

### ISSUE THREAD

**Issue by bstinsonmhk** [CentOS/python-cicoclient#10]
In ci.centos.org, we provision each workspace with a file called ~/.duffy.key that includes the appropriate API token, cicoclient should grab credentials from here (and perhaps fall back to using the environment if needed). 

This would make it harder to accidentally leak api keys in Jenkins shell jobs (which are set -xe by default)

**Comment by kbsingh** [comment]
Can we have it try in this order;
cli -> env constant -> ~/.duffy.key -> ~/duffy.key
